name: Push CSV to another repository

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  push_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Run Python script to generate CSVs
        run: python ejecutar_código.py

      - name: Push CSV to target repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_B_TOKEN }}
        with:
          source-directory: '*.csv'   # Todos los CSV generados
          destination-repo: 'jesusrobles824/Variables-macroeconomicas'
          target-branch: 'main'
          commit-message: 'Automated: Update CSV data'
