name: ejecutar código 2

on:
  schedule:
    - cron: "0 23 * * *"   # Todos los días a las 20:00 de Argentina (23:00 UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Checkout repo A
      - name: Checkout repo A
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas matplotlib numpy xlrd openpyxl

      # 4️⃣ Ejecutar script Python
      - name: Run script
        run: python ejecutar_código.py

      # 5️⃣ Configurar git en repo A
      - name: Configurar git en repo A
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 6️⃣ Guardar CSV en repo A
      - name: Guardar csv en repo A
        run: |
          git add *.csv
          git commit -m "Auto-update CSV $(date +'%Y-%m-%d %H:%M')" || echo "No hay cambios"
          git push

      # 7️⃣ Clonar repo B manualmente usando token
      - name: Clonar repo B
        run: |
          rm -rf repoB || true
          git clone https://x-access-token:${{ secrets.REPO_B_TOKEN }}@github.com/jesusrobles824/Variables-macroeconomicas.git repoB

      # 8️⃣ Copiar CSV a repo B
      - name: Copiar CSV al repo B
        run: |
          cp *.csv repoB/
          ls -l repoB/   # Verificar que los archivos están allí

      # 9️⃣ Commit y push en repo B
      - name: Commit y push en repo B
        run: |
          cd repoB
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update CSV desde repo A: $(date +'%Y-%m-%d %H:%M')" || echo "No hay cambios"
          git push
