name: Reservas Netas

on:
  schedule:
    # Todos los días a las 20:00 de Argentina (23:00 UTC)
    - cron: "0 23 * * *"
  workflow_dispatch: # Para correrlo manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar script
        run: python reservas_obligaciones_ooii.py

      - name: Configurar git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Guardar csv
        run: |
          git add Reservas_Netas.csv
          git commit -m "Auto-update: resultados $(date +'%Y-%m-%d %H:%M')" || echo "No hay cambios"
          git push
